# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: dotnet tool restore
  displayName: Restore tools

- script: dotnet restore
  displayName: Restore solution

- script: dotnet build
  displayName: Build solution

- script: >
    cd src/XUnit.Coverlet.Collector &&
    dotnet test --collect:"XPlat code coverage" --settings coverlet.runsettings &&
    cd TestResults/* &&
    mv coverage.opencover.xml $AGENT_BUILD_DIRECTORY/TestResults/coverage.opencover.xml &&
    cd $AGENT_BUILD_DIRECTORY
  displayName: Test solution
  env:
    AGENT_BUILD_DIRECTORY: $(Agent.BuildDirectory)

- script: tree
  displayName: Show build tree

#- script: >
#    dotnet csmacnz.Coveralls --opencover
#    -i $AGENT_BUILD_DIRECTORY/TestResults/coverage.opencover.xml
#    --repoToken $COVERALLS_REPO_TOKEN
#  displayName: Report test coverage
#  env:
#    AGENT_BUILD_DIRECTORY: $(Agent.BuildDirectory)
#    BUILD_BUILD_ID: $(Build.BuildId)
#    BUILD_REQUESTED_FOR: $(Build.RequestedFor)
#    BUILD_REQUESTED_FOR_EMAIL: $(Build.RequestedForEmail)
#    BUILD_SOURCE_BRANCH_NAME: $(Build.SourceBranchName)
#    BUILD_SOURCE_VERSION: $(Build.SourceVersion)
#    BUILD_SOURCE_VERSION_MESSAGE: $(Build.SourceVersionMessage)
#    COVERALLS_REPO_TOKEN: $(Coveralls.RepoToken)
